# Generated by Django 5.0.4 on 2024-04-22 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_remove_amenity_category_room_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="owner",
            field=models.ForeignKey(
                help_text="숙소의 주인을 선택하세요.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="숙소 주인",
            ),
        ),
    ]
